name: CI/CD workflow for Maven Build and Tomcat Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: List target folder
        run: ls -l target
 
      - name: Deploy to Tomcat
        run: |
         WAR_FILE=target/TrainBook-1.0.0-SNAPSHOT.war
         curl -v --upload-file "$WAR_FILE" \
         --user "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
          "${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/myapp&update=true"

